# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CFSDK-Sample-App-Objective-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CFSDK-Sample-App-Objective-C
	pod 'CFSDK', '3.0.0-beta'
end
